### ISSUE TITLE
Tab Key - File Input Focus

### ISSUE THREAD

**Issue by negativefix** [filamentgroup/jQuery-Custom-File-Input#1]
When custom file input gained focus after hitting the tab key, text label and the button of the input shifts upwards and disappear. I also come across this issue at demonstration page of the file input on filament group's website.  I had a chance to check it out with both Firefox and Chrome. Both generated the same result.

**Comment by Bramjetten** [comment]
This does not always occur for me. I'm not quite sure what triggers it exactly.

**Comment by frippz** [comment]
Checking the stylesheets, the selector `.customfile-input` has `position: absolute;` set, but no vertical offset, which might cause issues.

Stubbornella has mentioned this before:

> Using **absolute position, without setting horizontal and vertical offset**. For that reason, the absolutely positioned element will have the same position it would have had when set statically. However, if you try to manipulate the top, right, bottom, or left values, the element will all of the sudden be positioned relative to the nearest relatively positioned ancestor causing it to jump.

Adding `left: 0;` and `top: 0;` to that selector should work. It worked for me when I implemented this, at least.
