### ISSUE TITLE
Changes for Firefox

### ISSUE THREAD

**Issue by rochejul** [filamentgroup/jQuery-Custom-File-Input#2]
Hi,

I post here my version of your widget, where we manage somes specific case for Firefox (label, initialization ...).

Regards

$.fn.customFileInput = function(){
    //apply events and styles for file input element
    var fileInput = $(this)
        .addClass('customfile-input') //add class for CSS
        .css("top", "0px") // In Firefox, if we click on the associated label without having a hover on the input file, the display can be broken in some cases
        .css("left", "0px")
        .mouseover(function(){ upload.addClass('customfile-hover'); })
        .mouseout(function(){ upload.removeClass('customfile-hover'); })
        .focus(function(){
            upload.addClass('customfile-focus'); 
            fileInput.data('val', fileInput.val());
        })
        .blur(function(){ 
            upload.removeClass('customfile-focus');
            $(this).trigger('checkChange');
         })
         .bind('disable',function(){
            fileInput.attr('disabled',true);
            upload.addClass('customfile-disabled');
        })
        .bind('enable',function(){
            fileInput.removeAttr('disabled');
            upload.removeClass('customfile-disabled');
        })
        .bind('checkChange', function(){
            if(fileInput.val() && fileInput.val() != fileInput.data('val')){
                fileInput.trigger('change');
            }
        })
        .bind('change',function(){
            if($(this).val()){
                //get file name
                var fileName = $(this).val().split(/\/).pop();
                //get file extension
                var fileExt = 'customfile-ext-' + fileName.split('.').pop().toLowerCase();
                //update the feedback
                uploadFeedback
                    .text(fileName) //set feedback text to filename
                    .removeClass(uploadFeedback.data('fileExt') || '') //remove any existing file extension class
                    .addClass(fileExt) //add file extension class
                    .data('fileExt', fileExt) //store file extension for class removal on next change
                    .addClass('customfile-feedback-populated'); //add class to show populated state
                //change text of button 
                uploadButton.text('Change');

```
        } else {
            // For the reset form case
            uploadFeedback
                .text("No file selected...")
                .attr("class", "customfile-feedback");
            uploadButton.text('Browse');
        }

    })
    .click(function(event){ //for IE and Opera, make sure change fires after choosing a file, using an async callback
        fileInput.data('val', fileInput.val());
        setTimeout(function(){
            fileInput.trigger('checkChange');
        },100);
    });

if(fileInput.attr("id")){
    // Manage properly the click on the associated label (in Firefox, we can have some problems)
    $("label[for='" + fileInput.attr("id") + "']").live("click", function(event){
        event.preventDefault();
        event.stopImmediatePropagation();
        event.stopPropagation();
        fileInput.trigger('click');
    });
}

//create custom control container
var upload = $('<div class="customfile"></div>');
//create custom control button
var uploadButton = $('<span class="customfile-button" aria-hidden="true">Browse</span>').appendTo(upload);
//create custom control feedback
var uploadFeedback = $('<span class="customfile-feedback" aria-hidden="true">No file selected...</span>').appendTo(upload);

//match disabled state
if(fileInput.is('[disabled]')){
    fileInput.trigger('disable');
}


//on mousemove, keep file input under the cursor to steal click
upload
    .mousemove(function(e){
```

//          fileInput.css({
//              'left': e.pageX - upload.offset().left - fileInput.outerWidth() + 20, //position right side 20px right of cursor X)
//              'top': e.pageY - upload.offset().top - $(window).scrollTop() - 3
//          }); 

```
        fileInput.css({
            'left': e.pageX - upload.offset().left - fileInput.outerWidth() + 20, //position right side 20px right of cursor X)
            'top': e.pageY - upload.offset().top - 20
        }); 
    })
    .insertAfter(fileInput); //insert after the input

fileInput.appendTo(upload);

//return jQuery
return $(this);
```

};

**Comment by georgik** [comment]
I found interesting problem. The problem is also solved by part of code written rochejul.

I use jQuery 1.6.2.  
The problem is when you have file Browse button below currently visible part of page and you have to scroll down.
Browse button will stop reacting on hover events. The problem is in computation of 'top' coordinate.

rochejul's solution was to replace:
`'top': e.pageY - upload.offset().top - $(window).scrollTop() - 3`
by:
`'top': e.pageY - upload.offset().top - 20`

This is correct and it works for me. Tested with Google Chrome 17, Firefox 9, Internet Explorer 9, Safari 5.1
