### ISSUE TITLE
Any reason to trigger a change event on the fileInput? 

### ISSUE THREAD

**Issue by jlbruno** [filamentgroup/jQuery-Custom-File-Input#4]
I noticed that you manually triggering a change event on the file input, and wondering why? 

https://github.com/filamentgroup/jQuery-Custom-File-Input/blob/master/js/jQuery.fileinput.js#L33

For my app, I have another functioned bound to the change event which is getting called twice. I've commented out that line and things still seem to work fine, but wanted to make sure I wasn't missing something....

**Comment by scottjehl** [comment]
Hmm. Well, this code was written a couple of years ago so it's possible it's no longer needed. I'm assuming it was there because one browser or another didn't fire a change event on its own? We'd love a PR if you figure it out.

**Comment by jlbruno** [comment]
The comment below mentions IE and Opera, I tested IE8 with it commented out and seemed fine, but didn't test Opera. What would you be looking to support now?
