### ISSUE TITLE
Multiple Inputs

### ISSUE THREAD

**Issue by djapeman** [filamentgroup/jQuery-Custom-File-Input#5]
Hi,

Can anyone help me. I have an issue with implementing multiple file inputs and styling them with custom file input. It seams that all inputs are positioned over each other at the place of the first one. CSS changes are on their places, but inputs in the html are moved on the place of the first one?

Does anyone have solution for this issue?

Thanks in advance.

**Comment by sparkalyn** [comment]
If you are using a selector other than id to reference your inputs, you have to loop the function. So example.js changes from 

``` javascript
$(function(){
       $('#file').customFileInput();    
});
```

to 

``` javascript
 $(function() {

    $('.uploads input[type="file"]').each(function() {
        $(this).customFileInput();  
    }); 
 });    
```

Where the `.uploads input[type="file"]` is any selector matching more than one element.
